//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraderAI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TraderAI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,IntDate,Open,High,Low,Close,Adj Close,Volume
        ///3/24/1980,0,2.916667,2.916667,2.239583,2.541667,2.541667,3344400
        ///3/31/1980,1,2.541667,2.770833,2.520833,2.635417,2.635417,1432800
        ///4/7/1980,2,2.614583,2.770833,2.5,2.635417,2.635417,1538400
        ///4/14/1980,3,2.635417,2.645833,2.270833,2.322917,2.322917,2169600
        ///4/21/1980,4,2.322917,2.8125,2.28125,2.708333,2.708333,3043200
        ///4/28/1980,5,2.71875,2.791667,2.416667,2.46875,2.46875,1702800
        ///5/5/1980,6,2.5,2.729167,2.5,2.541667,2.541667,1180800
        ///5/12/1980,7,2.541667,2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AMD {
            get {
                return ResourceManager.GetString("AMD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,IntDate,Open,High,Low,Close,Adj Close,Volume
        ///5/13/1996,0,42.375,43,41.5,41.5,18.964882,403500
        ///5/20/1996,1,41.75,44.875,41.625,44.625,20.392954,2933100
        ///5/27/1996,2,45,46.375,44,45.75,20.907063,1955800
        ///6/3/1996,3,45.5,45.625,42,43.25,19.764601,1736400
        ///6/10/1996,4,43.125,43.5,42.375,42.375,19.364738,783500
        ///6/17/1996,5,42.375,42.625,38.75,39.5,18.050911,2419800
        ///6/24/1996,6,39.875,42.625,39.5,42.25,19.307615,2261000
        ///7/1/1996,7,42.25,45.125,42.25,42.375,19.364738,1644900
        ///7/8/1996,8,41.5,42.625,39.75 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TUP {
            get {
                return ResourceManager.GetString("TUP", resourceCulture);
            }
        }
    }
}
